### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by xingyujin-anyvision** [getchui/sample-apps#11]
Hey there, could you take a look at the issue please? do you have an idea on it
Traceback (most recent call last):
  File "demo_image.py", line 14, in <module>
    os.environ['TF_TOKEN'],
  File "/home/eddie/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'TF_TOKEN'
(trueface) eddie@an

**Comment by cyrusbehr** [comment]
Hi there,
Please export your SDK token into your shell before running the script.
`export TF_TOKEN=your_token`
